### PR TITLE
Updates sbt plugin and dep patch versions 

### PR DESCRIPTION
**Pull request by rubbish**
This upgrades our sbt plugins and adds a few. It also updates a few dependencies too to patch versions.

### CODE REVIEW

**Comment by rubbish** [comment]
Updating some of those depenedencies' minor versions will require some work. I'll create issues for that.

**Comment by adamdecaf** [comment]
👍

**Comment by zmccoy** [comment]
👍

**Comment by rubbish** [comment]
I need to update the changelog. Will do that and merge.

**Pull request merged**
