### PR TITLE
Bump jackson from 2.4.x to 2.6.x

### PR DESCRIPTION
**Pull request by adamdecaf**
Needed as we add logstash encoding to stdout https://github.com/Banno/logging-shim/pull/31

### CODE REVIEW

**Comment by adamdecaf** [comment]
We should likely bump this to be under a `1.4.x` release of jsonz.

**Comment by DustinChaloupka** [comment]
👍

**Comment by adamdecaf** [comment]
retest this please

**Comment by rubbish** [comment]
👍 to upgrade with bumping the version

**Comment by adamdecaf** [comment]
I'll merge this and release a new version.

**Comment by adamdecaf** [comment]
Released under https://github.com/Banno/jsonz/blob/master/CHANGELOG.md#140-unreleased

**Pull request merged**
