### PR TITLE
Updating jackson scala module to 2.6.6 from 2.4.1

### PR DESCRIPTION
**Pull request by zkay**
2.4.1 was causing strange test failures in kernel-admin and che, among others.

### CODE REVIEW

**Comment by rubbish** [comment]
@zkay Was there some other dependency that was added that forced it to conflict?

**Comment by zkay** [comment]
@rubbish Not in che, at least not directly. The last update to it's build.sbt was upgrading to the newest banno-sbt-plugin.

**Comment by rubbish** [comment]
Could it have been https://github.com/Banno/aws-utils/pull/49? We could find out by the ivy report xml or the dependency graph.

**Comment by BusyByte** [comment]
```bash
ESC[0m[ESC[0minfoESC[0m] ESC[0m  +-com.banno:aws-utils_2.10:1-SNAPSHOT [S]ESC[0m
ESC[0m[ESC[0minfoESC[0m] ESC[0m  | +-ch.qos.logback:logback-classic:1.1.3ESC[0m
ESC[0m[ESC[0minfoESC[0m] ESC[0m  | | +-ch.qos.logback:logback-core:1.1.3ESC[0m
ESC[0m[ESC[0minfoESC[0m] ESC[0m  | | +-org.slf4j:slf4j-api:1.7.12ESC[0m
ESC[0m[ESC[0minfoESC[0m] ESC[0m  | | ESC[0m
ESC[0m[ESC[0minfoESC[0m] ESC[0m  | +-ch.qos.logback:logback-core:1.1.3ESC[0m
ESC[0m[ESC[0minfoESC[0m] ESC[0m  | +-com.amazonaws:aws-java-sdk-s3:1.11.1ESC[0m
ESC[0m[ESC[0minfoESC[0m] ESC[0m  | | +-com.amazonaws:aws-java-sdk-core:1.11.1ESC[0m
ESC[0m[ESC[0minfoESC[0m] ESC[0m  | | | +-com.fasterxml.jackson.core:jackson-databind:2.6.6ESC[0m
ESC[0m[ESC[0minfoESC[0m] ESC[0m  | | | | +-com.fasterxml.jackson.core:jackson-annotations:2.6.0ESC[0m
ESC[0m[ESC[0minfoESC[0m] ESC[0m  | | | | +-com.fasterxml.jackson.core:jackson-core:2.6.6ESC[0m
```

I believe you are right @rubbish

**Comment by BusyByte** [comment]
that is from https://github.com/Banno/kernel-admin/pull/111 where I was seeing the issue also

**Comment by zkay** [comment]
Just to confirm things:

image

**Comment by BusyByte** [comment]
@zkay can you tell were 2.6 of fasterxml is being pulled in from?  I had to switch to text

**Comment by BusyByte** [comment]
`sbt dependencyTree`

**Comment by zkay** [comment]
@BusyByte It looks like by jsonz itself? It says some were evicted though:

```
[info]   | | +-jsonz:jsonz_2.10:1.0 [S]
[info]   | | | +-com.fasterxml.jackson.module:jackson-module-scala_2.10:2.4.1 [S]
[info]   | | | | +-com.fasterxml.jackson.core:jackson-annotations:2.4.1 (evicted by: 2.6.0)
[info]   | | | | +-com.fasterxml.jackson.core:jackson-annotations:2.6.0
[info]   | | | | +-com.fasterxml.jackson.core:jackson-core:2.4.1 (evicted by: 2.4.2)
[info]   | | | | +-com.fasterxml.jackson.core:jackson-core:2.4.2 (evicted by: 2.6.6)
[info]   | | | | +-com.fasterxml.jackson.core:jackson-core:2.6.6
[info]   | | | | +-com.fasterxml.jackson.core:jackson-databind:2.4.1.1 (evicted by: 2.4.2)
[info]   | | | | | +-com.fasterxml.jackson.core:jackson-annotations:2.4.0 (evicted by: 2.4.1)
[info]   | | | | | +-com.fasterxml.jackson.core:jackson-annotations:2.4.1 (evicted by: 2.6.0)
[info]   | | | | | +-com.fasterxml.jackson.core:jackson-annotations:2.6.0
[info]   | | | | | +-com.fasterxml.jackson.core:jackson-core:2.4.1 (evicted by: 2.4.2)
[info]   | | | | | +-com.fasterxml.jackson.core:jackson-core:2.4.2 (evicted by: 2.6.6)
[info]   | | | | | +-com.fasterxml.jackson.core:jackson-core:2.6.6
[info]   | | | | |
[info]   | | | | +-com.fasterxml.jackson.core:jackson-databind:2.4.2 (evicted by: 2.6.6)
[info]   | | | | | +-com.fasterxml.jackson.core:jackson-annotations:2.4.0 (evicted by: 2.4.1)
[info]   | | | | | +-com.fasterxml.jackson.core:jackson-annotations:2.4.1 (evicted by: 2.6.0)
[info]   | | | | | +-com.fasterxml.jackson.core:jackson-annotations:2.6.0
[info]   | | | | | +-com.fasterxml.jackson.core:jackson-core:2.4.2 (evicted by: 2.6.6)
[info]   | | | | | +-com.fasterxml.jackson.core:jackson-core:2.6.6
[info]   | | | | |
[info]   | | | | +-com.fasterxml.jackson.core:jackson-databind:2.6.6
[info]   | | | | | +-com.fasterxml.jackson.core:jackson-annotations:2.6.0
[info]   | | | | | +-com.fasterxml.jackson.core:jackson-core:2.6.6
```

**Comment by zkay** [comment]
@rubbish @BusyByte More info on it being from aws utils:

```
[0m[[0minfo[0m] [0m  | +-com.banno:aws-utils_2.10:1-SNAPSHOT [S][0m
[0m[[0minfo[0m] [0m  | | +-ch.qos.logback:logback-classic:1.1.3[0m
[0m[[0minfo[0m] [0m  | | | +-ch.qos.logback:logback-core:1.1.3[0m
[0m[[0minfo[0m] [0m  | | | +-org.slf4j:slf4j-api:1.7.12[0m
[0m[[0minfo[0m] [0m  | | | [0m
[0m[[0minfo[0m] [0m  | | +-ch.qos.logback:logback-core:1.1.3[0m
[0m[[0minfo[0m] [0m  | | +-com.amazonaws:aws-java-sdk-s3:1.11.1[0m
[0m[[0minfo[0m] [0m  | | | +-com.amazonaws:aws-java-sdk-core:1.11.1[0m
[0m[[0minfo[0m] [0m  | | | | +-com.fasterxml.jackson.core:jackson-databind:2.6.6[0m
[0m[[0minfo[0m] [0m  | | | | | +-com.fasterxml.jackson.core:jackson-annotations:2.6.0[0m
[0m[[0minfo[0m] [0m  | | | | | +-com.fasterxml.jackson.core:jackson-core:2.6.6[0m
[0m[[0minfo[0m] [0m  | | | | | [0m
[0m[[0minfo[0m] [0m  | | | | +-com.fasterxml.jackson.dataformat:jackson-dataformat-cbor:2.6.6[0m
[0m[[0minfo[0m] [0m  | | | | | +-com.fasterxml.jackson.core:jackson-core:2.6.6[0m
[0m[[0minfo[0m] [0m  | | | | | [0m
[0m[[0minfo[0m] [0m  | | | | +-joda-time:joda-time:2.8.1 (evicted by: 2.8.2)[0m
[0m[[0minfo[0m] [0m  | | | | +-joda-time:joda-time:2.8.2[0m
[0m[[0minfo[0m] [0m  | | | | +-org.apache.httpcomponents:httpclient:4.5.2[0m
[0m[[0minfo[0m] [0m  | | | |   +-commons-codec:commons-codec:1.9[0m
[0m[[0minfo[0m] [0m  | | | |   +-org.apache.httpcomponents:httpcore:4.4.4[0m
[0m[[0minfo[0m] [0m  | | | |   [0m
```

**Comment by zkay** [comment]
@rubbish What do you think we should do for this as a fix? Would it be better to force everything onto 2.6.6, since that is what aws-utils is pulling in (and evicting 2.4.x here and elsewhere)?

**Comment by InfernoJJ** [comment]
retest this please

**Comment by BusyByte** [comment]
I'm not sure if this project is versioned but do we want to bump the version on this?

**Comment by BusyByte** [comment]
jsonz 1.3-SNAPSHOT is what we are on right now

**Comment by InfernoJJ** [comment]
This result's in more dependency issues further down to the chain as well. Using a locally built snapshot of this branch I get this in Monitor.

[info] Done updating.
[error] Modules were resolved with conflicting cross-version suffixes in {file:/Users/jj/Documents/git_repos/sentinel/}sentinel-common:
[error]    io.spray:spray-httpx _2.10, <none>
[error]    io.spray:spray-util _2.10, <none>
[error]    io.spray:spray-io _2.10, <none>
[error]    io.spray:spray-http _2.10, <none>
java.lang.RuntimeException: Conflicting cross-version suffixes in: io.spray:spray-httpx, io.spray:spray-util, io.spray:spray-io, io.spray:spray-http

**Comment by zkay** [comment]
Closing this for now, can reopen in the future.

**Pull request closed without merging**
