### PR TITLE
Upgrade Build

### PR DESCRIPTION
**Pull request by juanpedromoreno**
This PR upgrades jackson and the scala version.

### CODE REVIEW

**Comment by rubbish** [comment]
@juanpedromoreno I don't know why jenkins was having such a hard time with the bintray credentials, but it is not required for this PR job anyways. I removed them from the jenkins configuration for this job  and it passed.

**Comment by juanpedromoreno** [comment]
Thanks @rubbish , should I expect to get 1.6.0 released automatically?

**Comment by rubbish** [comment]
@juanpedromoreno No, someone would need to publish that. I can try here locally. I haven't done a release of jsonz in ages.

**Comment by juanpedromoreno** [comment]
Thanks again @rubbish !

**Comment by rubbish** [comment]
I was able to get this to publish to bintray.

**Pull request merged**
